let data = {
    "home":{
        "description1": "Physical activity has numerous benefits for children and adolescents, including physiological and psychological benefits (Janssen & LeBlanc, 2010; Okely et al., 2012; Poitras et al., 2016), as well as cognitive and academic benefits (Bangsbo et al., 2016; Castelli et al., 2015; Hilman, Kamijo, & Scudder, 2011; Rasberry et al., 2011).According to the Australian Department of Health (2014), to achieve health benefits, children and adolescents should accumulate at least 60 minutes of moderate to vigorous intensity physical activity every day. This should include a variety of aerobic activities, including some vigorous intensity activity. Additionally, children and adolescents should engage in muscle and bone strengthening activities on at least three days per week. For additional health benefits, children and adolescents are advised to engage in more physical activity – up to several hours per day. However, according to the results of the 2016 Report Card on Physical Activity for Children and Young People, the majority of Australian children and young people are not meeting the daily Australian physical activity guidelines (Active Healthy Kids Australia [AHKA], 2016).Promoting healthy behaviours, such as physical activity engagement, and developing well-rounded individuals is a fundamental part of the role of schools. Schools are ideal settings for promoting physical activity because the vast majority of children attend school. Additionally, schools often have the necessary facilities for physical activity participation as well as personnel who are qualified or can be trained to facilitate physical activity opportunities. The critical role of schools in promoting physical activity has been highlighted by numerous organisations, including the World Health Organisation (2004, 2008).This instrument, the School Physical Activity Index (SPAI), was inspired by the School Health Index, a self-assessment and planning guide for schools that focuses on various aspects of school health and safety (Centers for Disease Control and Prevention, 2012). The SPAI, which focuses specifically on physical activity, is intended to be used as a self- assessment instrument that can help Australian primary schools:(a) identify their strengths and weaknesses in terms of their physical activity practices, and(b) develop a plan for improving their physical activity practices.This instrument can also be used to inform research projects targeting physical activity practices in Australian primary schools.",
        
        "description2":"The SPAI is based on a whole-of-school, multi-component approach to physical activity promotion in schools because such ecological approaches to physical activity promotion have been identified to have the largest potential impact. Accordingly, the questions included in this instrument are focused on multiple components as depicted in figure 1. Like in similar models developed worldwide (McMullen et al., 2015), Physical Education is considered the cornerstone of every school physical activity program. Along with Physical Education, the conceptual model for the SPAI includes three other components that represent the various school-based opportunities for students to be active (physical activity during school, physical activity before and after school, and active transport to/from school) as well as four enabling factors that are critical in supporting children’s physical activity engagement (staff involvement, family and community involvement, infrastructure, and funding). Finally, the model in Figure 1 advocates that a school physical program will more likely be effective when it is based on a plan developed, evaluated, and regularly updated by a school physical activity committee.",

    },
    "questionnaire":{
        "page":"Home",
        "description": " The AHKA (2016) Report Card on Physical Activity for Children and Young People recommends the delivery of at least 150 minutes per week of scheduled PE classes and organised school sports activities to all students, which are compulsory. For the purpose of this instrument, best practice is considered the delivery of 120 minutes of scheduled PE classes every week.In addition, the following are also used as indicators of best practice in this section:delivery of all scheduled PE classes for all students by a tertiary qualified PE specialist teacher.teacher/student ratio in PE lessons about the same to that of other subjects.a minimum of one professional development session per year specifically targeting PE for school staff who teach PE.not withholding PE as punishment."
    }
}

export default data;